name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    # Cette expression cron exécute le workflow tous les jours à 00:00 UTC (minuit)
    - cron: '0 0 * * *'  # Exécution tous les jours à minuit UTC
    

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] 
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Show Node.js version
        run: node -v  # Affiche la version de Node.js dans l'environnement CI

      # Install dependencies
      - name: Install dependencies
        run: |
          npm ci
          
      # Initialize Playwright
      - name: Initialize Playwright
        run: |
          npm init playwright@latest --yes

      # Install Playwright dependencies
      - name: Install Playwright browsers
        run: |
          npx playwright install --with-deps

      # Install Cucumber and related packages
      - name: Install Cucumber and Playwright-related packages
        run: |
          npm install @cucumber/cucumber
          npm install cucumber-html-reporter
          npm install pixelmatch pngjs
          npm install cross-env
          npm install ts-node typescript

      # Run tests (Cucumber and Playwright tests)
      - name: Run tests
        run: |
          npm run test
      - name: Send email with the test report
        if: always()  # Cette étape sera exécutée même si les tests échouent
        uses: dawidd6/action-send-mail@v3
        with:
          from: 'delplanquecyr@yahoo.fr'
          to: 'delplanquecyr@yahoo.fr'
          subject: 'CI Workflow Report'
          body: 'The CI workflow has completed. Please find the details of the report below.'
          attachments: 'reports/cucumber_report_chromium.html'  # Spécifiez le chemin du fichier de rapport
          smtp-server: 'smtp.mail.yahoo.com'
          smtp-username: ${{ secrets.YAHOO_EMAIL }}
          smtp-password: ${{ secrets.YAHOO_APP_PASSWORD }}
          smtp-port: 587  # Port standard pour SMTP via Yahoo
          smtp-secure: true  # Utilisation de la sécurité TLS
