name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] 
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: |
          npm ci
          
      # Initialize Playwright
      - name: Initialize Playwright
        run: |
          npm init playwright@latest --yes

      # Install Playwright dependencies
      - name: Install Playwright browsers
        run: |
          npx playwright install --with-deps

      # Install Cucumber and related packages
      - name: Install Cucumber and Playwright-related packages
        run: |
          npm install @cucumber/cucumber
          npm install cucumber-html-reporter
          npm install pixelmatch pngjs
          npm install cross-env
          npm install ts-node typescript

      # Run tests (Cucumber and Playwright tests)
      - name: Run tests
        run: |
          npm test
